ALTER TABLE "api_keys" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "app_menus" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "app_menus" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "apps" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "apps" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "health_check" ALTER COLUMN "checked_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "orgs" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "orgs" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "permission_groups" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "permission_groups" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "platform_settings" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "position_members" ALTER COLUMN "joined_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "positions" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "positions" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "role_permissions" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "tenant_users" ALTER COLUMN "joined_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "tenants" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "user_group_members" ALTER COLUMN "joined_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "user_groups" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "user_groups" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');